markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: Vienna Scala User Group
url: http://scala-vienna.org
description: The Vienna Scala User Group blog
twitter: ScalaVienna
github: scala-vienna
meetup: http://meetup.scala-vienna.org
